version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress --unsafe-perm -g npm
      - npm install --silent --no-progress --unsafe-perm -g serverless
  pre_build:
    commands:
      - npm install --no-progress --silent --unsafe-perm

artifacts:
  files:
    - **/*
    - serverless.yml
    - deploy.sh
  base-directory: .serverless
