version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - sudo npm install --unsafe-perm --no-progress --silent
      - mkdir -p target/stg
      - mkdir -p target/prod
      - serverless package --package target/stg --stage stg -v -r us-east-2
      - serverless package --package target/prod --stage prod -v -r us-east-2

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
