service: helloWorld

package:
  exclude:
    - node_modules/aws-sdk

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  stage: stg
  environment:
    STAGE: ${opt:stage}

custom:
  webpackIncludeModules: true
  stage: ${opt:stage}

functions:
  helloWorld:
    handler: handler.helloWorld
