service: helloworld

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  stage: stg
  environment:
    STAGE: ${opt:stage, self:provider.stage}

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  helloworld:
    handler: handler.helloworld
